# Generated by Django 3.2 on 2021-05-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='주차')),
                ('name', models.CharField(max_length=128, verbose_name='이름')),
                ('team', models.CharField(max_length=128, verbose_name='팀 이름')),
                ('lec_check', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=2, verbose_name='강의체크')),
                ('att_check', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=2, verbose_name='출석체크')),
                ('ass_check', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=2, verbose_name='과제체크')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막수정일')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '정보들',
                'db_table': 'Info_table',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='주차')),
                ('first', models.CharField(max_length=128, verbose_name='1등 팀')),
                ('second', models.CharField(max_length=128, verbose_name='2등 팀')),
                ('third', models.CharField(max_length=128, verbose_name='3등 팀')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막수정일')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '팀정보들',
                'db_table': 'Team_table',
            },
        ),
    ]
