# Generated by Django 3.2 on 2021-05-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_id',
            field=models.ForeignKey(db_column='team_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='Member.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_point',
            field=models.IntegerField(verbose_name='총점수'),
        ),
    ]
