# Generated by Django 3.2 on 2021-05-07 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_auto_20210507_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_id',
            field=models.ForeignKey(blank=True, db_column='team_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='Member.team'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='주차')),
                ('assignment', models.BooleanField(verbose_name='과제체크')),
                ('attendance', models.BooleanField(verbose_name='출석체크')),
                ('lecture', models.BooleanField(verbose_name='강의체크')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '점수',
                'verbose_name_plural': '점수들',
                'db_table': 'Score_talbe',
            },
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('user_id', 'week'), name='userAndweek'),
        ),
    ]
