# Generated by Django 3.2 on 2021-05-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_auto_20210507_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPoint',
            fields=[
                ('week', models.IntegerField(primary_key=True, serialize=False, verbose_name='주차')),
                ('first_team', models.ForeignKey(db_column='first_team', on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='Member.team')),
                ('second_team', models.ForeignKey(db_column='second_team', on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='Member.team')),
                ('third_team', models.ForeignKey(db_column='third_team', on_delete=django.db.models.deletion.CASCADE, related_name='third_team', to='Member.team')),
            ],
        ),
    ]
