# Generated by Django 3.2 on 2021-05-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_additionalpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalpoint',
            options={'verbose_name': '추가점수', 'verbose_name_plural': '추가점수들'},
        ),
        migrations.AlterModelTable(
            name='additionalpoint',
            table='AdditionalPoint_talbe',
        ),
    ]
